# Generated by Django 4.0.5 on 2022-06-24 18:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('marca_veiculo', models.CharField(max_length=50)),
                ('modelo_veiculo', models.CharField(max_length=100)),
                ('placa_veiculo', models.CharField(max_length=8)),
                ('km', models.PositiveIntegerField()),
                ('data_inicial', models.DateField(auto_now=True, verbose_name='Data')),
                ('data_termino', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Término')),
                ('observacoes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=100)),
                ('servico_id', models.PositiveIntegerField()),
                ('preco', models.FloatField()),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordem_de_servico.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('produto_id', models.PositiveIntegerField()),
                ('preco', models.FloatField()),
                ('quantidade', models.PositiveIntegerField()),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordem_de_servico.ordemservico')),
            ],
        ),
    ]
