# Generated by Django 4.0.5 on 2022-06-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_de_servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='os_concluida',
            field=models.BooleanField(default=False),
        ),
    ]
