# Generated by Django 4.0.5 on 2022-07-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_de_servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='valor_total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
