# Generated by Django 4.0.5 on 2022-07-07 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_de_servico', '0002_ordemservico_os_concluida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemservico',
            old_name='marca_veiculo',
            new_name='veiculo',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='modelo_veiculo',
        ),
    ]
