# Generated by Django 4.0.5 on 2022-07-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_de_servico', '0003_rename_marca_veiculo_ordemservico_veiculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='id_cliente',
            field=models.CharField(default='', max_length=50),
        ),
    ]
