# Generated by Django 4.0.5 on 2022-07-01 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
