# Generated by Django 4.0.5 on 2022-07-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=30)),
                ('preco_servico', models.FloatField()),
                ('descricao_servico', models.TextField()),
            ],
        ),
    ]
