# Generated by Django 4.0.5 on 2022-07-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50)),
                ('preco_produto', models.FloatField()),
                ('descricao_produto', models.CharField(max_length=250)),
                ('decricao_detalhada_produto', models.TextField()),
                ('imagem_produto', models.ImageField(blank=True, null=True, upload_to='produto_images/%Y/%m')),
                ('estoque', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('teste', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
